rule_files:
  - rule.yml
scrape_configs:
- job_name: node
  scrape_interval: 5s
  static_configs:
  - targets:
    - 35.156.225.236:9100
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
