services:
  nginx:
    image: nginx:1.27.3-alpine
    networks:
      - network
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./data/site:/var/www/html/
      - ./data/music:/var/www/html/music/
      - ./data/image:/var/www/html/image/
      - ../monitoring/logs:/var/log/nginx
    command: "sh -c 'chmod -R a+rx /var/www/html/ && nginx -g \"daemon off;\"'"
networks:
  network:
    driver: bridge
